
org.gradle.jvmargs=-Xmx1536m
android.useAndroidX=true

# POM content
POM_LIBRARY_NAME=Wultra Dynamic SSL pinning for Android
POM_DESCRIPTION=Android library implementing dynamic SSL pinning
POM_PACKAGING=aar
POM_SITE_URL=https://github.com/wultra/ssl-pinning-android
POM_SCM_CONNECTION_URL=scm:git:github.com/wultra/ssl-pinning-android.git
POM_SCM_URL=https://github.com/wultra/ssl-pinning-android
POM_DEVELOPER_ID=wultra
POM_DEVELOPER_NAME=Wultra s.r.o.
POM_DEVELOPER_EMAIL=support@wultra.com
POM_LICENSE_NAME=Apache License Software License, Version 2.0
POM_LICENSE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
