# Note that following values are just placeholders. You need to provide valid configuration or
# all the tests will fail.
#
# You can also use "private-integration-tests.properties" file for your own configuration.

test.sslPinning.baseUrl=https://my-mus-deployment.com
test.sslPinning.appName=my-app-name
