name: Lint

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Lint
        run: ./gradlew library:lint

      - name: Upload lint results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-results-debug
          path: library/build/reports/lint-results-debug.html
          retention-days: 5
